### ISSUE TITLE
Create RR Roadmap

### ISSUE THREAD

**Issue by fadidahanna** [fadidahanna/redisraft#1]
- [ ] roadmap preparation toward a meeting with Alon
- [ ] meet with Alon
- [ ] present the roadmap to Yossi to get final approval
- [ ] preset the roadmap to Gidon and Eyal
- [ ] preset the roadmap to the team
